[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[[hints.enabled]]
action = "Copy"
mouse = { enabled = true }
binding = { key = "L", mods = "Control|Shift" }
# regex = "(?<=--- a)[^ ]*"
# regex = "(?<=hh((---|\\+\\+\\+) [ab]))[^ ]*"
# regex = "([.\\w\\-~\\$@]+)?(/[.\\w\\-@]+)+(\\:\\d)*(\\(\\d,\\d\\))*{10,}"
# regex = "([.\\w\\-~\\$@]+)?(/[.\\w\\-@]+)+(\\:\\d)*(\\(\\d,\\d\\))*"
regex = "[a-f0-9]{7,40}|(([.\\w\\-~\\$@]+)?(/[.\\w\\-@]+)+(\\:\\d)*(\\(\\d,\\d\\))*)|(---|\\+\\+\\+) [ab]/(?<match>.*)"
