theme = "github_dark"

[editor]
mouse = true
auto-completion = false
auto-pairs = false
idle-timeout = 1000
gutters = ["line-numbers"]
auto-save = true
cursorline = true
bufferline = "multiple"
clipboard-provider = "pasteboard"

[editor.inline-diagnostics]
cursor-line = "disable"

[keys.normal.space.i]
c = ":toggle inline-diagnostics.cursor-line hint"
C = ":toggle inline-diagnostics.cursor-line disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal._] # change case
u = "switch_to_uppercase"
l = "switch_to_lowercase"
p = ":pipe caseify Pascal"
c = ":pipe caseify Camel"
s = ":pipe caseify Snake"
d = ":pipe caseify Dot"
k = ":pipe caseify Kebab"
t = ":pipe caseify Capitalised"
o = ":pipe caseify Sentence"
n = ":pipe caseify Constant"

[keys.normal]
ins = "insert_mode"
tab = ":bn"
S-tab = ":bp"
C-S-up = "increment"
C-S-down = "decrement"
C-up = "expand_selection"
C-down = "shrink_selection"
C-left = "select_prev_sibling"
C-right = "select_next_sibling"
"@" = "goto_word"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.insert]
C-space = "completion"
C-right = "move_next_word_start"
C-left = "move_prev_word_start"

[editor.search]
smart-case = false

[editor.lsp]
auto-signature-help = false

[editor.soft-wrap]
enable = true
